<h3><?= $this->translate('Please enter the code on your Google Authenticator app'); ?></h3>

<?php
$this->authCodeForm->setAttribute('action', $this->url('doctrine-auth/2fa/authenticate'));
$this->formElementErrors()->setAttributes(['class' => 'errors']);
$this->authCodeForm->prepare();
echo $this->form()->openTag($this->authCodeForm);
?>
<div class="enter-code">
    <p><?= $this->translate('Please enter the code on your authentication app'); ?></p>
    <div class="code">
        <?= $this->formText($this->authCodeForm->get('code')) ?>
        <?= $this->formElementErrors($this->authCodeForm->get('code')); ?>
    </div>
    <div class="submit">
        <?= $this->formElement($this->authCodeForm->get('csrf')) ?>
        <?= $this->formElementErrors($this->authCodeForm->get('csrf')); ?>
        <?= $this->formSubmit($this->authCodeForm->get('submit')) ?>
    </div>
</div>
<?= $this->form()->closeTag(); ?>
