<!DOCTYPE html>
<html>
    <head>
        <title><?= $this->translate('Login code'); ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>
                        <h1><?= $this->siteName; ?></h1>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <p><?= $this->translate('A single use login authentication code has been requested.'); ?></p>
                        <p><?= sprintf($this->translate('Your code is %s. Please enter this on the login page.'), $this->code); ?></p>
                        <p><?= sprintf($this->translate('This code will expire in %d'), $this->expires); ?> <?= $this->translatePlural('minute', 'minutes', $this->expires); ?></p>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><?= $this->translate('If you did not request this code then your account password has been compromised, please login an change your password as soon as possible.'); ?></p>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
