<?php
/**
 * @var PhpRenderer|ViewHelperTrait|HelperTrait|I18nHelperTrait $this
 * @var int $passwordLinkActiveFor
 * @var string $code
 * @var string $siteName
 **/

use FwsDoctrineAuth\View\Helper\ViewHelperTrait;
use Laminas\Form\View\HelperTrait;
use Laminas\I18n\View\HelperTrait as I18nHelperTrait;
use Laminas\View\Renderer\PhpRenderer;

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><?= $this->translate('Password Reset'); ?></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>
                        <h1><?= $siteName; ?></h1>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <p><?= sprintf($this->translate('A password reset has been requested, this link is active for %d hours.'), $passwordLinkActiveFor); ?></p>
                        <p><a href="<?= $this->url('doctrine-auth/password-reset', ['code' => $code], ['force_canonical' => TRUE,]); ?>"><?= $this->url('doctrine-auth/password-reset', ['code' => $code], ['force_canonical' => TRUE,]); ?></a></p>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>

