<!DOCTYPE html>
<html>
    <head>
        <title>Password Reset</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>
                        <h1><?= $this->siteName; ?></h1>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <p>A password reset has been requested.</p>
                        <p><a href="<?= $this->url('doctrine-auth/passwordReset', ['code' => $this->code], ['force_canonical' => TRUE,]); ?>"><?= $this->url('doctrine-auth/passwordReset', ['code' => $this->code], ['force_canonical' => TRUE,]); ?></a></p>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>

