<h2><?php echo $this->translate('Reset Password'); ?></h2>
<?php
$this->formElementErrors()->setAttributes(array('class' => 'errors'));
if ($this->emailForm) {
    $this->emailForm->setAttribute('action', $this->url('doctrine-auth/passwordReset'));
    echo $this->partial('form.phtml', ['form' => $this->emailForm]);
} elseif ($this->resetForm) {
    $this->resetForm->setAttribute('action', $this->url('doctrine-auth/passwordReset', array('code' => $this->code)));
    echo $this->partial('form.phtml', ['form' => $this->resetForm]);
} elseif ($this->emailSent === true) {
    echo '<p>' . $this->translate('An password reset link has been sent') . '</p>'
    . '<p><a href="' . $this->url('doctrine-auth/default', ['action' => 'login']) . '">' . $this->translate('Return to login') . '</a></p>';
} elseif ($this->emailSent === false) {
    echo '<p>' . $this->translate('Unable to send password reset link') . '</p>'
    . '<p><a href="' . $this->url('doctrine-auth/default', ['action' => 'login']) . '">' . $this->translate('Return to login') . '</a></p>';
} elseif ($this->invalidLink === true) {
    echo '<p>' . $this->translate('This link is invalid or has expired') . '</p>'
    . '<p><a href="' . $this->url('doctrine-auth/default', ['action' => 'login']) . '">' . $this->translate('Return to login') . '</a></p>';
} elseif ($this->passwordReset === true) {
    echo '<p>' . $this->translate('Your new password has been set') . '</p>'
    . '<p><a href="' . $this->url('doctrine-auth/default', ['action' => 'login']) . '">' . $this->translate('Return to login') . '</a></p>';
} elseif ($this->passwordReset === false) {
    echo '<p>' . $this->translate('Unable to set your new password') . '</p>'
    . '<p><a href="' . $this->url('doctrine-auth/default', ['action' => 'login']) . '">' . $this->translate('Return to login') . '</a></p>';
}
?>