<h2><?php echo $this->translate('Register'); ?></h2>
<?php
$this->form->setAttribute('action', $this->url('doctrine-auth/default', array('action' => 'register')));
$this->formElementErrors()->setAttributes(array('class' => 'errors'));
echo $this->partial('form.phtml', ['form' => $this->form]);
if ($this->errorMessage) {
    echo '<p class="error">' . $this->errorMessage . '</p>' . PHP_EOL;
}